version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "create-subscriber:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  gateway:
    build: ./api-gateway
    command: "sh -c 'npm install && npm run start:dev'"
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - kafka
      - mongo
  subscriber:
    build: ./subscriber
    command: "sh -c 'npm install && npm run start:dev'"
    ports:
      - "3001:3001"
    volumes:
      - .:/home/node/app
    depends_on:
      - kafka
      - mongo
